- .gitignore
- final/.classpath
- final/.project
- final/src/main/java/com/project/app/common/Constants.java
.classpath, .project, delete Constants.java and add gitignore
> initial set

- final/.classpath
- final/src/main/webapp/WEB-INF/views/header/header.jsp
> fix : 헤더 수정

- final/src/main/webapp/WEB-INF/views/footer/footer.jsp
- final/src/main/webapp/WEB-INF/views/main/index.jsp
> style : index.jsp 수정

- final/src/main/resources/application.yml
> fix : db 변경

- antico/src/main/webapp/WEB-INF/views/review/all_reviews.jsp
> [feat] 전체 후기 수정

- antico/pom.xml
1. pom.xml에서 컴파일 시 paramter 설정 추가
> [feat] 자바 컴파일 설정 변경

- antico/src/main/webapp/WEB-INF/views/header/header.jsp
1. 메인로고를 클릭하면 메인페이지로 이동하는 기능 추가
> [feat] : 메인로고 이동 기능 추가

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO_imple.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> feat: view단 페이지 제작

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/domain/ProductVO.java
- antico/src/main/java/com/project/app/product/mapper/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
1. 상품 등록 view 페이지 생성
2. header 페이지 판매하기 버튼 링크 수정
> [feat] 상품 등록 view 페이지 생성

- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> feat: 공유하기 모달 추가

- antico/src/main/java/com/project/app/product/domain/ProductImageVO.java
- antico/src/main/java/com/project/app/product/domain/ProductVO.java
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
1. 상픔 등록 view 페이지 업데이트
2. ProductVO / ProductImageVO 생성
> [feat] : 상품 등록 view 페이지 업데이트

- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
1. com.project.app.product.mapper -> com.project.app.product.model
> [chore] : Product mapper 패키지명 변경

- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
메인 내 상품 hover 위치조정, 사이드바 hover
> feat: mypage 프론트

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/domain/MemberVO.java
- antico/src/main/java/com/project/app/member/service/CustomAccessHandler.java
- antico/src/main/java/com/project/app/member/service/CustomEntryPoint.java
- antico/src/main/java/com/project/app/member/service/CustomUserDetails.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/member/service/MemberService_imple.java
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
1. 비로그인 회원 핸들러 생성
2. 테이블변경에 따른 MemberVO 변경
3. MemberVO 변경에 따른 회원 변수 변경
> feat:비로그인 회원 핸들러 생성

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/domain/CategoryDetailVO.java
- antico/src/main/java/com/project/app/product/domain/CategoryVO.java
- antico/src/main/java/com/project/app/product/domain/ProductImageVO.java
- antico/src/main/java/com/project/app/product/domain/ProductVO.java
- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/resources/mybatis/mybatis-config.xml
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
1. 이미지 미리보기 업데이트
2. 테이블 변경에 따른 상품/상품이미지/카테고리상위/카테고리하위 VO 업데이트 
3. mybatis-config.xml 상품 관련 VO 추가
> [chore] : 상품 등록 페이지 이미지 미리보기 업데이트

- antico/src/main/java/com/project/app/member/controller/MemberController.java
> chore:MemberVO변경에 따른 컨트롤러 변경

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/service/CustomUserDetails.java
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/webapp/WEB-INF/views/main/login.jsp
- antico/src/main/webapp/WEB-INF/views/main/register.jsp
> fix:에러로 인한 주석처리

- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
마이페이지에서 공유하기 버튼을 누르면 해당 url 복사, 인스타그램 로그인 화면으로 이동
> feat: 공유하기

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/pointcharge.jsp
- antico/src/main/webapp/js/mypage/pointcharge.js
> feat: 포인트충전view

- antico/src/main/resources/application.yml
1. vm option 직접 지정에서 환경변수를 통한 비밀번호 지정으로 변경
> [refact] : jasypt password 수정 

- .github/workflows/deploy.yml
> [build] : deploy.yml 수정

- .github/workflows/deploy.yml
1. 빌드 시 yml의 jasypt password에 값이 저장되도록 변경
> [build] deploy.yml 수정

- antico/src/main/webapp/WEB-INF/views/mypage/memberDelete.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> feat: 회원탈퇴 nav

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/domain/ProductImageVO.java
- antico/src/main/java/com/project/app/product/domain/ProductVO.java
- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/add_success.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist.jsp
1. 상품 등록 기능 추가
2. 상품 등록 완료 페이지 생성
3. header 페이지 전체 폰트 패밀리 CSS 추가
> [feat] : 상품 등록 기능 추가 및 header 페이지 폰트 추가

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
- antico/src/main/java/com/project/app/member/model/MemberDAO.java
- antico/src/main/java/com/project/app/member/service/CustomAccessHandler.java
- antico/src/main/java/com/project/app/member/service/CustomEntryPoint.java
- antico/src/main/java/com/project/app/member/service/CustomUserDetails.java
- antico/src/main/java/com/project/app/member/service/LoginFailureHandler.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/member/service/MemberService_imple.java
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
> fix:로그인 기능 에러 수정

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/application.yml
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/resources/static/js/pointcharge.js
- antico/src/main/webapp/WEB-INF/views/mypage/myBank.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/pointcharge.jsp
계좌관리 view 페이지 제작 완료.
변경버튼 클릭이벤트(ajax)와 정산내역 클릭이벤트(ajax)부터 시작하면 됨
> style: 계좌관리 view

- antico/src/main/java/com/project/app/common/GetMemberDetail.java
- antico/src/main/java/com/project/app/member/service/CustomUserDetails.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
1. 멤버상세 필드 삭제 후 MemberVO 타입 필드로 변경
2. 로그인시 마이페이지 이동
> chore:멤버상세 수정 및 뷰단 수정

- antico/src/main/webapp/WEB-INF/views/tab/tab.jsp
> [feat] : tab 사이드바 css 재변경

- antico/src/main/java/com/project/app/common/GetMemberDetail.java
- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
1. 값이 없는곳에서 형변환을 하려해 형변환 에러 나오는 부분 수정
> fix: 로그인시 형변환에러 수정

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
- antico/src/main/java/com/project/app/member/domain/MemberVO.java
- antico/src/main/java/com/project/app/member/service/CustomAccessHandler.java
- antico/src/main/java/com/project/app/member/service/CustomEntryPoint.java
- antico/src/main/java/com/project/app/member/service/LoginFailureHandler.java
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/resources/static/js/member/cookie.js
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
- antico/src/main/webapp/WEB-INF/views/main/register.jsp
1.회원가입 쿼리문 수정
2. 회원가입 뷰단 변경.
3. 시큐리티 필터 수정(더 수정이 필요합니다.)
> chore:회원가입 수정, 시큐리티 필터 수정

- antico/src/main/java/com/project/app/component/GetMemberDetail.java
- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/member/service/MemberService_imple.java
- antico/src/main/java/com/project/app/security/CustomAccessHandler.java
- antico/src/main/java/com/project/app/security/CustomEntryPoint.java
- antico/src/main/java/com/project/app/security/CustomUserDetails.java
- antico/src/main/java/com/project/app/security/LoginFailureHandler.java
1. 시큐리티 핸들러를 시큐리티패키지로 위치 변경
2. 유저정보를 담는 메소드 컴포넌트 패키지로 위치변경
> chore:파일 위치변경

- antico/src/main/java/com/project/app/component/S3FileManager.java
> [feat] : S3 이미지 다중 업로드 기능 추가

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/add_success.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/tab/tab.jsp
1. 상품 등록 이미지 추가 방식 변경 (S3)
2. 상품 조회 페이지 작성 (업데이트중)
3. tab.jsp z-index 값 수정
> [feat] : 상품 등록 이미지 추가 방식 변경 (S3)

- antico/src/main/java/com/project/app/member/model/MemberDAO.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/memberDelete.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
탈퇴 신청 이후 72시간 안에 로그인하면 탈퇴신청 취소, 72시간 이후는 회원상태 탈퇴로 업데이트 현재 오류는 탈퇴 후 다시 로그인하여 탈퇴신청을 다시 할 때 에러발생
> feat: 탈퇴하기 기능

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
> [feat] : 상품 정보 조회 메소드 추가

- antico/src/main/java/com/project/app/product/model/ProductMapper.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
> [chore] : 상품 조회 메소드 수정

- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/resources/mybatis/mapper/member.xml
> fix : 회원탈퇴 수정중

- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/memberDelete.jsp
재탈퇴시 에러 수정 완료 및 로그인시 status 체크하고 0이면 로그인 불가
> fix: 탈퇴하기 에러수정완료

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/resources/static/js/pointcharge.js
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/pointcharge.jsp
> feat: 마이페이지 회원정보 불러오기

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/pointcharge.jsp
현재 충전테이블 insert
회원의 포인트 update 완료 되었습니다.
> feat: 포인트충전 완료

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
일정 금액에 비례하여 회원의 등급 변경 및 회원의 해당등급의 퍼센트 추출
> feat: 회원의 등급

- antico/src/main/java/com/project/app/comment/controller/CommentController.java
- antico/src/main/java/com/project/app/inquire/controller/InquireController.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
기존 => 포인트 충전금액으로 환산한 점수
현재 => 실버까지만 충전금액 -> 실버에서 골드 등급업은 신뢰지수 포함
충전금액은 max 70퍼까지만
> fix: 등급 재설정

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
> feat: 판매자정보페이지 제작

- antico/src/main/java/com/project/app/admin/controller/AdminController.java
- antico/src/main/java/com/project/app/admin/model/AdminDAO.java
- antico/src/main/java/com/project/app/admin/service/AdminService.java
- antico/src/main/java/com/project/app/admin/service/AdminService_imple.java
- antico/src/main/java/com/project/app/comment/controller/CommentController.java
- antico/src/main/java/com/project/app/inquire/controller/InquireController.java
- antico/src/main/resources/mybatis/mapper/admin.xml
- antico/src/main/webapp/WEB-INF/views/admin/admin_notice_delete.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_uninquire_list.jsp
> feat: 공지사항삭제

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
> fix : 에러 주석처리

- antico/pom.xml
- antico/src/main/java/com/project/app/config/KakaoLoginConfig.java
- antico/src/main/java/com/project/app/member/controller/KakaoLoginController.java
- antico/src/main/java/com/project/app/member/controller/KakaoLoginPageController.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
- antico/src/main/java/com/project/app/member/domain/KakaoLoginVO.java
- antico/src/main/java/com/project/app/member/domain/KakaoTokenResponseVO.java
- antico/src/main/java/com/project/app/member/domain/KakaoUserInfoResponseVO.java
- antico/src/main/java/com/project/app/member/service/KakaoLoginService.java
- antico/src/main/java/com/project/app/review/controller/ReviewController.java
- antico/src/main/resources/application.yml
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/main/login.jsp
> feat:카카오 로그인 기능구현

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_deatil.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
1. 상품 조회 페이지 view페이지 완성 및 카테고리 조회 기능 추가
2. header 페이지 검색 기능 -> 상품 목록 페이지 이동
> [feat] : 상품 목록 페이지 카테고리 조회 기능 추가

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
> fix: point_sum 에러

- antico/src/main/java/com/project/app/component/GetMemberDetail.java
- antico/src/main/java/com/project/app/member/controller/KakaoLoginController.java
- antico/src/main/java/com/project/app/member/controller/MemberController.java
- antico/src/main/java/com/project/app/member/domain/KakaoUserInfoResponseVO.java
- antico/src/main/java/com/project/app/member/model/MemberDAO.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/member/service/MemberService.java
- antico/src/main/java/com/project/app/member/service/MemberService_imple.java
- antico/src/main/java/com/project/app/security/LoginFailureHandler.java
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/main/login.jsp
1.카카오 로그인시 시큐리티로 인증 인가 처리.
2. 카카오 로그인시 바로 이동을 위해 뷰단 투가
> feat:카카오 로크인 시큐리티 연동 추가

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist_lat_lng.jsp
1. 상품 목록 페이지 검색 필터 보완
2. 좋아요 기능 추가
> [feat] : 상품 목록 페이지 검색 필터 보완, 좋아요 기능 추가

- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> fix: 마이페이지, 판매자페이지 파싱

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
> feat: 판매자 페이지 상품 띄우기

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
1. 상품 상세 페이지 메소드 타입 수정
2. header 검색 form CSS 수정
> [chore] 상품 상세 페이지 메소드 타입 수정

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
> [chore] 상품 상세 페이지 변수명 수정

- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/review/model/ReviewDAO.java
- antico/src/main/java/com/project/app/review/service/ReviewService_imple.java
- antico/src/main/java/com/project/app/trade/controller/TradeController.java
- antico/src/main/java/com/project/app/trade/domain/TradeVO.java
- antico/src/main/java/com/project/app/trade/model/TradeDAO.java
- antico/src/main/java/com/project/app/trade/service/TradeService.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/resources/mybatis/mybatis-config.xml
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/trade/show_payment.jsp
판매상세에서 구매하기 클릭시 상품상태 체크 후 구매가 가능한지 검사 및 가능하다면 사이드탭 띄우기까지.
> feat: 구매하기

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist_lat_lng.jsp
1. 상품 상세 페이지 상태 변경 기능 추가
2. mypage 공유 아이콘 수정
> [feat] : 상품 상세 페이지 상태 변경 기능 추가

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
- antico/src/main/webapp/WEB-INF/views/trade/show_payment.jsp
판매상품이 없을 때 마이페이지 안 들어가진 에러 수정완료.
> fix: 마이페이지 에러 수정

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist_lat_lng.jsp
> [feat] : 상품 목록 페이지 지역 검색 추가

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
마이페이지 들어갈시 favicon.ico 에러 해결완료
> fix: 마이페이지 에러

- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
> [feat] : 상품 상세 페이지 판매자 정보 추가_수정

- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
- antico/src/main/webapp/WEB-INF/views/trade/show_payment.jsp
판매상품이 없을 때 로그인 후 마이페이지 이동시 셀러페이지로 이동 해결 완료,
헤더 인크루드 삭제하고 탈퇴하기 해결완료
> fix: 탈퇴하기 에러, sellerpage 에러

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/buyList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
> chore: 판매내역 상세필터

- antico/src/main/java/com/project/app/index/controller/IndexController.java
- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/domain/ProductVO.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/resources/static/css/paging.css
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
- antico/src/main/webapp/WEB-INF/views/paging.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/add_success.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist_lat_lng.jsp
1. 상품 상세 페이지 조회수 기능 추가
2. paging css 수정
3. 메인페이지 상품 조회 추가
> [feat] : 상품 상세 페이지 조회수 기능 추가

- antico/src/main/java/com/project/app/trade/controller/TradeController.java
- antico/src/main/java/com/project/app/trade/model/TradeDAO.java
- antico/src/main/java/com/project/app/trade/service/TradeService.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/resources/mybatis/mapper/trade.xml
구매확정 클릭시 판매자 포인트 증가 업데이트, 판매상태를 구매확정으로 업데이트, 구매상태를 결제확정으로 업데이트, 포인트내역에 사용정보 insert
> chore: 구매확정 클릭시

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
1. 경매 판매 선택 시 회원 등급 실버 미만일 경우 경고 메시지 추가
2. 상품 판매 페이지 경매 등록 추가
3. 경매 시작 일자 유효성 검사 추가
> [feat] : 상품 판매 페이지 경매 등록 추가

- antico/.classpath
- antico/src/main/java/com/project/app/admin/controller/AdminController.java
- antico/src/main/java/com/project/app/admin/model/AdminDAO.java
- antico/src/main/java/com/project/app/admin/service/AdminService.java
- antico/src/main/java/com/project/app/admin/service/AdminService_imple.java
- antico/src/main/java/com/project/app/comment/controller/CommentController.java
- antico/src/main/java/com/project/app/inquire/service/InquireService_imple.java
- antico/src/main/resources/mybatis/mapper/admin.xml
- antico/src/main/webapp/WEB-INF/views/admin/admin_member_management.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_notice_delete.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_page.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_product_detail.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_product_list.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_sidemenu.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_statistics.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_uninquire_list.jsp
- antico/src/main/webapp/WEB-INF/views/notice/notice_list.jsp
관리자가 상품조회 및 상품상세보기 기능.
관리자가 통계(방문자 , 매출, 카테고리별 상품조회) 보는 기능
유저조회 페이징처리, 상품조회 페이징 처리
> feat: 관리자상품관리, 통계 docs:관리자페이지

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/update.jsp
1. 상품 삭제 기능 추가
2. 상품 수정 페이지 생성
3. 이미지 등록 오류 수정
> [feat] : 상품 삭제 기능 추가

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/member/model/MemberDAO.java
- antico/src/main/java/com/project/app/security/CoustomSuccessHandle.java
- antico/src/main/resources/application.yml
- antico/src/main/resources/mybatis/mapper/member.xml
- antico/src/main/resources/mybatis/mybatis-config.xml
> feat:로그인 기록남기기

- antico/src/main/java/com/project/app/member/model/MemberDAO.java
- antico/src/main/java/com/project/app/member/service/MemberDetailService.java
- antico/src/main/resources/mybatis/mapper/member.xml
72시간 체크 업데이트가 안 되고 있어서 전체적인 틀을 바꿔서 수정했습니다.
현재 정상적으로 동작
> fix: 탈퇴하기 기능에러 수정

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist_lat_lng.jsp
- antico/src/main/webapp/WEB-INF/views/product/update.jsp
1. 상품 수정 기능 추가
2. 상품 페이지 경매 관련 view 페이지 수정
> [feat] : 상품 수정 기능 추가  / 상품 페이지 경매 관련 수정

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/buyList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/buy_info.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellList.jsp
판매내역과 구매내역 모든 기능 완성했습니다. 후기 이어붙이면 됩니다.
> feat: 구매내역

- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
> chore: tab.jsp

- antico/src/main/java/com/project/app/review/controller/ReviewController.java
- antico/src/main/java/com/project/app/review/model/ReviewDAO.java
- antico/src/main/java/com/project/app/review/service/ReviewService.java
- antico/src/main/java/com/project/app/review/service/ReviewService_imple.java
- antico/src/main/resources/mybatis/mapper/review.xml
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
1. 판매자 페이지에서 후기 조회  기능 연결
2. 이미 후기를 작성했을 경우 예외처리 추가
> [feat] : 판매자 페이지 후기 조회  기능 연결

- antico/src/main/java/com/project/app/chat/controller/ChatController.java
- antico/src/main/java/com/project/app/chat/domain/Chat.java
- antico/src/main/java/com/project/app/chat/service/ChatService.java
- antico/src/main/java/com/project/app/chat/service/ChatService_imple.java
- antico/src/main/java/com/project/app/component/ProductSaleStatusEventListener.java
- antico/src/main/webapp/WEB-INF/views/chat/chat.jsp
- antico/src/main/webapp/WEB-INF/views/chat/chat_main.jsp
1. 경매 시작 시 경매 채팅방 생성 기능 추가
2. 판매 상태 변경 알림 채팅 스타일 수정
> [feat] : 경매 채팅방 생성 기능

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
회원과 3번 이상 거래한 회원이 존재한다면 단골회원으로 처리
> feat: 거래횟수와 단골

- antico/src/main/java/com/project/app/review/controller/ReviewController.java
- antico/src/main/java/com/project/app/review/model/ReviewDAO.java
- antico/src/main/java/com/project/app/review/service/ReviewService.java
- antico/src/main/java/com/project/app/review/service/ReviewService_imple.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
- antico/src/main/resources/mybatis/mapper/review.xml
- antico/src/main/webapp/WEB-INF/views/mypage/buyList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellList.jsp
> [feat] : 판매내역/구매내역 후기 조회 추가

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/market_price.jsp
> [feat] : 시세조회 페이지 생성 및 기능 추가

- antico/src/main/java/com/project/app/auction/controller/AuctionController.java
- antico/src/main/java/com/project/app/auction/domain/AucChatRoomRespDTO.java
- antico/src/main/java/com/project/app/auction/domain/AuctionBid.java
- antico/src/main/java/com/project/app/auction/domain/AuctionChat.java
- antico/src/main/java/com/project/app/auction/domain/AuctionChatRoom.java
- antico/src/main/java/com/project/app/auction/domain/AuctionVO.java
- antico/src/main/java/com/project/app/auction/model/AuctionDAO.java
- antico/src/main/java/com/project/app/auction/repository/AuctionBidRepository.java
- antico/src/main/java/com/project/app/auction/repository/AuctionChatRepository.java
- antico/src/main/java/com/project/app/auction/repository/AuctionChatRoomRepository.java
- antico/src/main/java/com/project/app/auction/repository/CustomAuctionChatRoomRepository.java
- antico/src/main/java/com/project/app/auction/service/AuctionService.java
- antico/src/main/java/com/project/app/auction/service/AuctionService_imple.java
- antico/src/main/java/com/project/app/chat/controller/ChatController.java
- antico/src/main/java/com/project/app/chat/domain/Chat.java
- antico/src/main/java/com/project/app/chat/domain/Participant.java
- antico/src/main/java/com/project/app/chat/service/ChatService.java
- antico/src/main/java/com/project/app/chat/service/ChatService_imple.java
- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/java/com/project/app/scheduler/AuctionScheduler.java
- antico/src/main/resources/mybatis/mapper/auction.xml
- antico/src/main/resources/mybatis/mybatis-config.xml
- antico/src/main/resources/static/js/chat/Chat.js
- antico/src/main/resources/static/js/custom_toast.js
- antico/src/main/webapp/WEB-INF/views/chat/auction_chat.jsp
- antico/src/main/webapp/WEB-INF/views/chat/chat_main.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
채팅방 목록 조회 시 일반 채팅, 경매 채팅으로 분류하여 이벤트에 따라 ajax로 조회하도록 수정
경매 채팅 조회 기능 삭제
일반 채팅과 도메인 분리
경매 입장 알림, 경매 채팅, 참여자 정보 조회, 입찰가 저장, 경매 종료 기능 추가
> [feat] : 경매 기능 추가

- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mybank_list.jsp
> backup: 계좌관리

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/market_price.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/regionlist.jsp
1. 메인페이지 검색어 자동완성
2. 상품 상세페이지 (거래량/후기/단골 조회)
3. 상품 등록 시 가격 (경매 -> 입찰 가격)
> [feat] : 메인페이지 검색어 자동완성

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/security/CustomAccessHandler.java
- antico/src/main/java/com/project/app/security/CustomEntryPoint.java
- antico/src/main/resources/static/js/custom_toast.js
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/notice/notice_list.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
1. 채팅 인가처리
2. 문의내역 인가처리
3. 상품관련 인가처리
> chore:인가처리 추가

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/edit_bank.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/myBank.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mybank_list.jsp
> feat: 계좌관리-> 사용내역

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
> [fix] : 상품 페이지(목록/상세) 비로그인 조회 수정

- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
처음에는 20개를 보여주고 더보기 클릭시 20개를 더 보여주며, 최종적으로 리스트를 다 보여주었을 때 더보기 버튼은 숨기도록 완성
> feat: 마이페이지 메인 더보기

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/admin/admin_page.jsp
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/notice/notice_list.jsp
- antico/src/main/webapp/WEB-INF/views/product/wish_list.jsp
> feat:찜한상품보기

- antico/src/main/java/com/project/app/admin/controller/AdminController.java
- antico/src/main/java/com/project/app/inquire/controller/InquireController.java
- antico/src/main/java/com/project/app/notice/controller/NoticeController.java
- antico/src/main/webapp/WEB-INF/views/admin/admin_detailcalendar.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_editcalendar.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_insertcalendar.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_member_management.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_notice_delete.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_page.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_product_detail.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_product_list.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_searchcalendar.jsp
- antico/src/main/webapp/WEB-INF/views/inquire/inquire_add.jsp
- antico/src/main/webapp/WEB-INF/views/inquire/inquire_detail.jsp
> style: css 수정

- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
> fix:찜한 상품 연결

- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/trade/controller/TradeController.java
- antico/src/main/webapp/WEB-INF/views/mypage/buyList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/buy_info.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/edit_bank.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/memberDelete.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/myBank.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mybank_list.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/pointcharge.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
> chore: 불필요한 주석 제거

- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
> fix: 예약중인 상품

- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
- antico/src/main/webapp/WEB-INF/views/product/market_price.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
1. header 페이지 상품 검색 함수명 변경
2. 상품 목록 페이지 카테고리 테이블 숨기기 보이기 수정
> [fix] : header 페이지 상품 검색 함수명 변경

- antico/src/main/java/com/project/app/auction/controller/AuctionController.java
- antico/src/main/java/com/project/app/auction/service/AuctionService_imple.java
- antico/src/main/java/com/project/app/component/ProductSaleStatusEventListener.java
- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/resources/static/js/custom_toast.js
- antico/src/main/webapp/WEB-INF/views/chat/auction_chat.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/review/register.jsp
1. 판매자 경매 종료 시 실시간으로 참여자 경매 종료 처리
2. 판매자 경매 종료 시 1대1 결제 채팅방 미생성 오류 수정
3. 후기 내역 유효성 검사 추가
4. 실버 미만 회원이 경매 참가 시 경고 알림 처리
5. 경매 시작 전에 참가 시 경고 알림 처리
6. 후기 상세 조회 시 구매자/판매자 표시
> [fix] : 경매 종료 오류 수정, 후기 내역 유효성 검사 추가, 경매 참가 유효성 처리 추가

- antico/src/main/java/com/project/app/auction/service/AuctionService_imple.java
- antico/src/main/java/com/project/app/scheduler/AuctionScheduler.java
- antico/src/main/resources/static/js/custom_toast.js
- antico/src/main/resources/static/js/sse/sse.js
- antico/src/main/webapp/WEB-INF/views/chat/auction_chat.jsp
- antico/src/main/webapp/WEB-INF/views/chat/chat_main.jsp
- antico/src/main/webapp/WEB-INF/views/header/header.jsp
1. 경매 낙찰 알림 추가
2. 채팅방 목록에 상품 제목 추가
> [feat] : 경매 낙찰 알림 추가, 채팅방 목록에 상품 제목 추가

- antico/src/main/java/com/project/app/config/SecurityConfig.java
- antico/src/main/java/com/project/app/index/controller/IndexController.java
- antico/src/main/java/com/project/app/member/domain/MemberVO.java
- antico/src/main/java/com/project/app/security/CoustomSuccessHandle.java
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
- antico/src/main/webapp/WEB-INF/views/main/register.jsp
1. 회원가입 유효성 검사 문제 수정
2. 정지된 호원 로그아웃 시키며 토스트 알람 전송
> fix:회원가입 수정, 정지회원 인가처리

- antico/src/main/java/com/project/app/admin/model/AdminDAO.java
- antico/src/main/java/com/project/app/admin/service/AdminService_imple.java
- antico/src/main/resources/mybatis/mapper/admin.xml
- antico/src/main/webapp/WEB-INF/sql/antico.sql
- antico/src/main/webapp/WEB-INF/views/admin/admin_editcalendar.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_page.jsp
- antico/src/main/webapp/WEB-INF/views/admin/admin_searchcalendar.jsp
일일방문자 수 통계 쿼리문 수정
캘린더 유효성 검사 수정
> fix: 통계 및 유효성 검사

- antico/src/main/java/com/project/app/exception/ExceptionCode.java
- antico/src/main/java/com/project/app/mypage/controller/MypageController.java
- antico/src/main/java/com/project/app/mypage/model/MypageDAO.java
- antico/src/main/java/com/project/app/mypage/service/MypageService.java
- antico/src/main/java/com/project/app/mypage/service/MypageService_imple.java
- antico/src/main/java/com/project/app/trade/model/TradeDAO.java
- antico/src/main/java/com/project/app/trade/service/TradeService_imple.java
- antico/src/main/resources/mybatis/mapper/mypage.xml
- antico/src/main/resources/mybatis/mapper/trade.xml
- antico/src/main/webapp/WEB-INF/views/mypage/buyList.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/buy_info.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- antico/src/main/webapp/WEB-INF/views/mypage/sellerpage.jsp
거래 취소 중복 취소 및 구매확정시 취소가 되는 에러 해결, 받은 후기 개수 셀렉, 마이페이지 상품개수 상태별로 분할 완료
> fix: 거래 취소, 구매확정 오류

- antico/src/main/java/com/project/app/product/controller/ProductController.java
- antico/src/main/java/com/project/app/product/model/ProductDAO.java
- antico/src/main/java/com/project/app/product/service/ProductService.java
- antico/src/main/java/com/project/app/product/service/ProductService_imple.java
- antico/src/main/resources/mybatis/mapper/product.xml
- antico/src/main/webapp/WEB-INF/views/main/index.jsp
- antico/src/main/webapp/WEB-INF/views/product/add.jsp
- antico/src/main/webapp/WEB-INF/views/product/prod_detail.jsp
- antico/src/main/webapp/WEB-INF/views/product/prodlist.jsp
1. 차단사용자 상품 조회 제한
2. 상품 등록페이지 상품명/상품상세내용 XSS 방어 추가
3. 경매완료 오버레이 추가
> [fix] : 차단사용자 상품 조회 제한
